version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/app/data

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.frontend
    ports:
      - "80:80"

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "8081:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  backend-data:
